version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - '3000:3000'
    env_file: .env
    networks:
      - boiler-network
    depends_on:
      - mysql
      - redis
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: boiler-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: test2
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - '3308:3306'
    networks:
      - boiler-network
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: boiler-redis
    ports:
      - '6379:6379'
    networks:
      - boiler-network
    volumes:
      - redis_data:/data
    restart: unless-stopped

networks:
  boiler-network:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
